### ISSUE TITLE
ImportError: No module named 'fused'

### ISSUE THREAD

**Issue by fradino** [KelestZ/Latent2im#6]
hello，i have some problem when installing.
![图片](https://user-images.githubusercontent.com/31378961/132357948-a4c0805e-7dee-4c4a-8fe2-1328273f7e38.png)
![图片](https://user-images.githubusercontent.com/31378961/132358008-4a27e043-b62a-4c6c-a6fe-af5209d20677.png)

**Comment by KelestZ** [comment]
Hi, you may need to upgrade your GCC version >=4.9. 
Similar issues can be found here:
https://github.com/rosinality/stylegan2-pytorch/issues/247
https://github.com/rosinality/stylegan2-pytorch/issues/220

**Comment by KelestZ** [comment]
> hello，i have some problem when installing.
> ![图片](https://user-images.githubusercontent.com/31378961/132357948-a4c0805e-7dee-4c4a-8fe2-1328273f7e38.png)
> ![图片](https://user-images.githubusercontent.com/31378961/132358008-4a27e043-b62a-4c6c-a6fe-af5209d20677.png)

Hi, you may need to upgrade your GCC version >=4.9.
Similar issues can be found here:
rosinality/stylegan2-pytorch#247
rosinality/stylegan2-pytorch#220

**Comment by fradino** [comment]
i just upgraded my gcc to 8.3.1 but it still doesn't work
![图片](https://user-images.githubusercontent.com/31378961/132435781-8c1c1eb0-475a-4ee1-82fe-fe62e2970e43.png)

**Comment by fradino** [comment]
> 
> 
> > hello，i have some problem when installing.
> > ![图片](https://user-images.githubusercontent.com/31378961/132357948-a4c0805e-7dee-4c4a-8fe2-1328273f7e38.png)
> > ![图片](https://user-images.githubusercontent.com/31378961/132358008-4a27e043-b62a-4c6c-a6fe-af5209d20677.png)
> 
> Hi, you may need to upgrade your GCC version >=4.9.
> Similar issues can be found here:
> [rosinality/stylegan2-pytorch#247](https://github.com/rosinality/stylegan2-pytorch/issues/247)
> [rosinality/stylegan2-pytorch#220](https://github.com/rosinality/stylegan2-pytorch/issues/220)

![图片](https://user-images.githubusercontent.com/31378961/132435833-ca8a55e5-ce98-4815-9f6e-f52f37955645.png)
i just upgraded my gcc to 8, but still doesn't work

**Comment by fradino** [comment]
> 
> 
> > > hello，i have some problem when installing.
> > > ![图片](https://user-images.githubusercontent.com/31378961/132357948-a4c0805e-7dee-4c4a-8fe2-1328273f7e38.png)
> > > ![图片](https://user-images.githubusercontent.com/31378961/132358008-4a27e043-b62a-4c6c-a6fe-af5209d20677.png)
> > 
> > 
> > Hi, you may need to upgrade your GCC version >=4.9.
> > Similar issues can be found here:
> > [rosinality/stylegan2-pytorch#247](https://github.com/rosinality/stylegan2-pytorch/issues/247)
> > [rosinality/stylegan2-pytorch#220](https://github.com/rosinality/stylegan2-pytorch/issues/220)
> 
> ![图片](https://user-images.githubusercontent.com/31378961/132435833-ca8a55e5-ce98-4815-9f6e-f52f37955645.png)
> i just upgraded my gcc to 8, but still doesn't work

ok，i solved this problem by replacing the c++ implement by pytorch implement

**Comment by KelestZ** [comment]
> hi. i have the same problem, can you tell how to solve this problem specifically please?

Hi, do the solutions aforementioned in this issue work for me?
1) Your gcc version should be >=4.9.
 Similar issues can be found here:
 https://github.com/rosinality/stylegan2-pytorch/issues/247
 https://github.com/rosinality/stylegan2-pytorch/issues/220

2) You can replace c++ implementation using PyTorch code. (You may find them in the github issue of https://github.com/rosinality/stylegan2-pytorch/issues/247)
 
Please let me know if you still have questions.
