### ISSUE TITLE
How to edit multiple attributes at the same time?

### ISSUE THREAD

**Issue by songquanpeng** [KelestZ/Latent2im#9]
Hi,

Firstly thank you for the awesome work!

I want to edit multiple attributes at the same time. But currently, I still don't figure it out. Would you like to share some start script examples which demonstrate how to do this?

Thank you very much for your time!

Best regards, 
JustSong

**Comment by KelestZ** [comment]
Hi, thanks for your interest and sorry for the late reply. 
I uploaded a file named "train_multi_attr.py" for training multiple attributes at a time. Basically, you can control the target attributes to be trained at a time via the "attrList" flag. The default setting is to train on all 40 attributes.
For visualization, I was using the two functions "vis_multi_image_batch_alphas_combine" and "vis_multi_image_batch_alphas" in transform_base.py. 

I didn't run this script at this time point but feel free to ping me if it's not runnable or has any issues.

Beyond that, I'd like to mention that from my old experiments, the combination of attributes could be tricky. There are conflict attributes in the dataset, e.g., summer and winter in the scene dataset. To jointly train them, one needs to carefully design their weights. For instance, if randomly assign 0.9 and 0.9 for them, the model may get confused to produce an image with both strong summer and winter attributes. However, this could be the next step in improving the method.

**Comment by songquanpeng** [comment]
Thx for you reply! I will look into it.

**Comment by songquanpeng** [comment]
And is it convenient for you to share the weight for the 40 attributes? It will save a lot of time if okay.
